require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'

target 'EvoltMobileApp' do
  config = use_native_modules!

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'MyFiziqSDKBilling', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-ios-billing', :branch => '19.1.16_trunk'
  pod 'MyFiziqSDK', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-ios', :branch => '19.1.16_trunk'
  pod 'MyFiziqSDKCommon', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-common', :branch => '19.1.16_trunk'
  pod 'MyFiziqSDKSupport', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-support', :branch => '19.1.16_trunk'
  pod 'MyFiziqSDKOnboardingView', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-onboardingview', :branch => '19.1.16_trunk'
  pod 'MyFiziqSDKTrackingView', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-trackingview', :branch => '19.1.16_trunk'
  pod 'MyFiziqSDKProfileView', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-profileview', :branch => '19.1.16_trunk'
  pod 'MyFiziqSDKInputView', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-inputview', :branch => '19.1.16_trunk'
  pod 'MyFiziqSDKLoginView', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-loginview', :branch => '19.1.16_trunk'
  pod 'MyFiziqPractiseSDK', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-practise', :branch => '19.1.9_trunk'
  pod 'MyFaCSS', :git => 'https://github.com/MyFiziqApp/InterfaCSS.git', :branch => '19.1.6_trunk'
  pod 'MyFiziqSDKCoreLite', :git => 'https://external-myfiziq-at-175889021455:Nf1Hwj3e77INg5cqytVri1tvXM0tzUyN63AuUAievL4%3D@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-ios-lite', :branch => '19.1.16_trunk'
  pod 'SpotHeroEmailValidator', '2.0.0'

  use_react_native!(:path => config["reactNativePath"])

  target 'EvoltMobileAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'EvoltMobileApp-tvOS' do
  # Pods for EvoltMobileApp-tvOS

  target 'EvoltMobileApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
